name: Build project and validate formatting

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: adopt
        java-version: 11
    - name: Set up Maven
      uses: stCarolas/setup-maven@v4.2
      with:
        maven-version: 3.8.1
    - name: Build project
      run: mvn test -B
    - name: Validate formatting
      run: mvn validate formatter:validate
    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Artifact
        path: build/libs/*.jar
